// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Touchstone.Data;

namespace Touchstone.Migrations
{
    [DbContext(typeof(TouchstoneContext))]
    [Migration("20201214022034_initiaalCreate")]
    partial class initiaalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Touchstone.Models.Batch", b =>
                {
                    b.Property<int>("batchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("batchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branch_ID")
                        .HasColumnType("int");

                    b.Property<int?>("branch_objbranchID")
                        .HasColumnType("int");

                    b.Property<string>("courseCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("batchID");

                    b.HasIndex("branch_objbranchID");

                    b.ToTable("Batch");
                });

            modelBuilder.Entity("Touchstone.Models.Branch", b =>
                {
                    b.Property<int>("branchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("branchAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("branchID");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("Touchstone.Models.Student", b =>
                {
                    b.Property<int>("studentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("studentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("studentMobile")
                        .HasColumnType("int");

                    b.Property<string>("studentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tutor_ID")
                        .HasColumnType("int");

                    b.Property<int?>("tutor_objtutorID")
                        .HasColumnType("int");

                    b.HasKey("studentID");

                    b.HasIndex("tutor_objtutorID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Touchstone.Models.Tutor", b =>
                {
                    b.Property<int>("tutorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("branch_ID")
                        .HasColumnType("int");

                    b.Property<int?>("branch_objbranchID")
                        .HasColumnType("int");

                    b.Property<string>("tutorAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tutorMobile")
                        .HasColumnType("int");

                    b.Property<string>("tutorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tutorID");

                    b.HasIndex("branch_objbranchID");

                    b.ToTable("Tutor");
                });

            modelBuilder.Entity("Touchstone.Models.Batch", b =>
                {
                    b.HasOne("Touchstone.Models.Branch", "branch_obj")
                        .WithMany()
                        .HasForeignKey("branch_objbranchID");
                });

            modelBuilder.Entity("Touchstone.Models.Student", b =>
                {
                    b.HasOne("Touchstone.Models.Tutor", "tutor_obj")
                        .WithMany()
                        .HasForeignKey("tutor_objtutorID");
                });

            modelBuilder.Entity("Touchstone.Models.Tutor", b =>
                {
                    b.HasOne("Touchstone.Models.Branch", "branch_obj")
                        .WithMany()
                        .HasForeignKey("branch_objbranchID");
                });
#pragma warning restore 612, 618
        }
    }
}
